package org.drools.devguide.cep;

import org.drools.devguide.cep.HeartAttackEvent;
import org.drools.devguide.cep.HeartBeatEvent;

rule "No heart beat in the last 5 seconds!"

when
    not (
            HeartBeatEvent()
            over windows:time(5s)
        )
then 
    System.out.println("===Know the Symptoms of a Heart Attack====");
    insert (new HeartAttackEvent());
    drools.halt();
end 
