package org.drools.devguide.cep;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
import org.kie.api.definition.type.Expires;
import org.kie.api.definition.type.Role;

@Role(Role.Type.EVENT)
@Expires("10m")
public class HeartBeatEvent implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HeartBeatEvent() {
        super();
    }




}